### ISSUE TITLE
edit-createOrder-page

### ISSUE THREAD

**Issue by SergeBrakow** [SergeBrakow/neuefische-capstone-project-Cibri#11]
## Value Proposition
As an **user** 
I want **to have a page** 
so that **I can create a new entry for an order**. 

## Acceptance criteria
- [ ] you can set a title
- [ ] you can set a time 
- [ ] you can set a date 
- [ ] you can make notes

## Tasks
- [ ] create a form
- [ ] for input time
- [ ] for input name
- [ ] for input note
- [ ] create button save 
- [ ] create navigation /createOrder/11.11.2022

## Size
medium
