### ISSUE TITLE
create-edit-page

### ISSUE THREAD

**Issue by SergeBrakow** [SergeBrakow/neuefische-capstone-project-Cibri#13]
## Value Proposition
As an **user** 
I want **to have a page** 
so that **I can edit an order**. 

## Acceptance criteria
- [ ] you can set a title
- [ ] you can set a time 
- [ ] you can set a date 
- [ ] you can make notes

## Tasks
- [ ] create a form
- [ ] for input time
- [ ] for input name
- [ ] for input note
- [ ] create button save 
- [ ] autofill the inputs
- [ ] save changes local storage
- [ ] navigate to home back 

## Size
medium
