### ISSUE TITLE
fix-long-texts

### ISSUE THREAD

**Issue by SergeBrakow** [SergeBrakow/neuefische-capstone-project-Cibri#16]
## Value Proposition
As an **user** 
I want ** i want to enter long texts** 
so that **they are displayed correctly**. 

## Acceptance criteria
- [ ] i can see all inserted texts completely without any broken sites/elements

## Tasks
- [ ] define style ( word-break: break-word; ) in layout
- [ ] fix missing width size in buttons text elements

## Size
medium
