### ISSUE TITLE
delete-order

### ISSUE THREAD

**Issue by SergeBrakow** [SergeBrakow/neuefische-capstone-project-Cibri#17]
## Value Proposition
As an **user** 
I want **to have an option** 
so that **I can delete an order**. 

## Acceptance criteria
- [ ] i can delete an order entry

## Tasks
- [ ] create a button in edit-page
- [ ] add a deleteOrder functionality to the button
- [ ] delete order from orderList

## Size
smal
