### ISSUE TITLE
link-user

### ISSUE THREAD

**Issue by SergeBrakow** [SergeBrakow/neuefische-capstone-project-Cibri#21]
## Value Proposition
As an **user** 
I want **to have a option in the order** 
so that **I can link other user**. 

## Acceptance criteria
- [ ] i can see available user
- [ ] i can choose some user and link them

## Tasks
- [ ] show user from the userList
- [ ] mark already linked user
- [ ] ad onClick function to mark/ unmark user
- [ ] save linked user in the order

## Size
medium
