### ISSUE TITLE
page-new-assignment

### ISSUE THREAD

**Issue by SergeBrakow** [SergeBrakow/neuefische-capstone-project-Cibri#5]
## Value Proposition
As an **user** 
I want **to have a page** 
so that **I can create a new entry for an assignment**. 

## Acceptance criteria
- [ ] you can set a name
- [ ] you can set a time 
- [ ] you can the creators name 

## Description
![image](https://user-images.githubusercontent.com/45800906/199926791-2b89b0eb-9d0e-4e94-8d0d-1782910b5e3b.png)

## Tasks
- [ ] create a form
- [ ] for input time
- [ ] for input name
- [ ] for textinput note
- [ ] create buttons save and cancel
- [ ] save the new entry in local storage

## Size
small

**Comment by s-kond** [comment]
as acceptance criteria I would add the note input - everything else is easy to understand and looks fine to me 👍

**Comment by SergeBrakow** [comment]
> as acceptance criteria I would add the note input - everything else is easy to understand and looks fine to me 👍

done :)
